<div align="center"><h1>Login do Sistema</h1>    
</div>
<div class="jumbotron" align="center">

    
<?php

    echo $this->form()->openTag($form);

?>

<table width='350'>
    <tr>
        <td width='60'>Login: </td>
        <td><?php echo $this->formRow($form->get('login'));?></td>
    </tr>
    <tr>
        <td>Senha: </td>
        <td><?php echo $this->formElement($form->get('senha'));?></td>
    </tr>
    <tr>
        <td></td>
        <td><?php echo strip_tags($this->formElementerrors($form->get('senha')));?></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td><?php  echo $this->formRow($form->get('logar'));?></td>
    </tr>
    
</table>

<?php

echo $this->form()->closeTag();

?>
    
</div>
