<?php

echo $this->form()->openTag($form);
echo $this->formRow($form->get('id')); 
?>

<table width='500'>
    <tr>
        <td width='60'>Título: </td>
        <td><?php echo $this->formRow($form->get('title'));?></td>
    </tr>
    <tr>
        <td>Artista: </td>
        <td><?php  echo $this->formRow($form->get('artist')); ?></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td><?php  echo $this->formRow($form->get('enviar'));?></td>
    </tr>
</table>

<?php

echo $this->form()->closeTag();

?>