<?php

echo $this->form()->openTag($form);



echo $this->formRow($form->get('id')); 



?>

<table width='500'>
    <tr>
        <td width='60'>Título: </td>
        <td><?php echo $this->formRow($form->get('title'));?></td>
    </tr>
    <tr>
        <td>Artista: </td>
        <td><?php echo $this->formElement($form->get('artist'));?></td>
    </tr>
    <tr>
        <td></td>
        <td><?php echo strip_tags($this->formElementerrors($form->get('artist')));?></td>
    </tr>
    <tr>
        <td>Imagem: </td>
        <td><?php  echo $this->formRow($form->get('arq_imagem')); ?></td>
    </tr>
    <tr>
        <td>Txt: </td>
        <td><?php  echo $this->formRow($form->get('arq_texto')); ?></td>
    </tr>
    <?php
    if(!empty($erro))
    {
    ?>
    <tr>
        <td>&nbsp;</td>
        <td>
            <ul>
               <li>
                   <?php  echo $erro;?>
               </li>
            </ul>
        </td>
    </tr>
    <?php
    }
    ?>
    <tr>
        <td>&nbsp;</td>
        <td><?php  echo $this->formRow($form->get('enviar'));?></td>
    </tr>
    
</table>

<?php

echo $this->form()->closeTag();

?>