<?php
 // module/Album/view/album/album/delete.phtml:

 $title = 'Delete album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Você tem certeza que deseja deletar o registro?
     '<?php echo $this->escapeHtml($album->title); ?>' de
     '<?php echo $this->escapeHtml($album->artist); ?>'?
 </p>
 
 <form action="" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $album->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>

