<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Edit album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php

 //$id = $this->params('id');
 echo $this->id;
 
 //echo $this->form->element->id;
 
 $form = $this->form;

 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('title'));
 echo $this->formRow($form->get('artist'));
 echo $this->formSubmit($form->get('enviar'));
 echo $this->form()->closeTag();
 
 ?>