<?php
 // module/Album/view/album/album/index.phtml:

//Mudar Layout
//$this->layout()->setTemplate('album/layout');
//Deixar layout por módulo http://akrabat.com/zend-framework-2/module-specific-layouts-in-zf2/
//Alterar no global.php
//Colocar a rota nos module.config de cada modulo pros layouts especificos

 $title = 'My albums';
 $this->headTitle($title);
 
 
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="/album/add">Add new album</a>
 </p>

 <table class="table">
 <tr>
     <th><a href="/album/page/<?php echo $pagina;?>/type/title/order/<?php echo $ordem; ?>">Title</a></th>
     <th><a href="/album/page/<?php echo $pagina;?>/type/artist/order/<?php echo $ordem; ?>">Artist</a></th>
     <th><a href="/album/page/<?php echo $pagina;?>/type/tipo/order/<?php echo $ordem; ?>">Tipo</a></th>
     <th>&nbsp;</th>
 </tr>
 <?php 
 
 foreach ($this->paginator as $album) : 
 
 //Imprime as colunas com seus respectivos valores
 //print_r($album);
 
 ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->title);?></td>
     <td><?php echo $this->escapeHtml($album->artist);?></td>
     <td><?php echo $this->escapeHtml($album->midia);?></td>
     <td>
         <a href="/album/edit/id/<?php echo $album->id;?>">Edit</a>
         <a href="/album/delete/id/<?php echo $album->id;?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
 
<?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object
     $this->paginator,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     'partial/paginator.phtml',
     // the route to link to when a user clicks a control link
     array(
         'route' => 'album'
     )
 );
 ?>